# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlRMQI2ibgYNauaPtmqE_aZXV7RzESic
"""

#Task 4

def max_activities(activities, M):
    activities.sort(key=lambda x: x[1])
    people = [-1] * M
    total_activities = 0

    for activity in activities:
        for i in range(M):
            if people[i] <= activity[0]:
                people[i] = activity[1]
                total_activities += 1
                break

    return total_activities

inp = open('input4.txt', 'r')
oup = open('output4.txt', 'w')

N, M = map(int, inp.readline().split())
activities = [list(map(int, line.split())) for line in inp]

max_activity_count = max_activities(activities, M)

oup.write(f"{max_activity_count}")

inp.close()
oup.close()