# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNL6ba9NhQ1uycY0FbHwEvCpQLVV1h2k
"""

#1) Can you write an O(N^2) Solution to solve the problem?
#Code here

inp = open("input1_1.txt", "r")
out = open("output1_1.txt", "w")

n, s = map(int, inp.readline().split())
list_of_numbers = list(map(int, inp.readline().split()))


flag = 0

for x in range(n):
    for y in range(n):
        if y != x:
            if list_of_numbers[x] + list_of_numbers[y] == s:
                out.write(f"{x + 1} {y + 1}\n")
                flag = 1
                break
    if flag:
        break

if flag != 1:
    out.write("IMPOSSIBLE\n")


inp.close()
out.close()