# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlRMQI2ibgYNauaPtmqE_aZXV7RzESic
"""

#Task 02: 2) Come up with a solution which runs in O(n).
#Code here


inp = open('input2_2.txt', 'r')
oup = open('output2_2.txt', 'w')
k1 = list(map(int, inp.readline().strip().split()))
k2 = list(map(int, inp.readline().strip().split()))
k3 = list(map(int, inp.readline().strip().split()))
k4 = list(map(int, inp.readline().strip().split()))

l = []
x = 0
y = 0

while x < k1[0] and y < k3[0]:
    if k2[x] <= k4[y]:
        l.append(k2[x])
        x += 1
    else:
        l.append(k4[y])
        y += 1

l.extend(k2[x:])

l.extend(k4[y:])

for elem in l:
    oup.write(str(elem) + " ")

oup.close()
inp.close()