# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlRMQI2ibgYNauaPtmqE_aZXV7RzESic
"""

#Task 02: 1) Find a solution which runs in O(nlogn).
#Code here

inp = open("input2_1.txt","r")
oup = open("output2_1.txt","w")
k1 = list(map(int,inp.readline().strip().split(" ")))
k2 = list(map(int,inp.readline().strip().split(" ")))
k3 = list(map(int,inp.readline().strip().split(" ")))
k4 = list(map(int,inp.readline().strip().split(" ")))
newlistt = k2 + k4
sortedlist=sorted(newlistt)
for x in sortedlist:
  oup.write(str(x)+ " ")

inp.close()
oup.close()