# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlRMQI2ibgYNauaPtmqE_aZXV7RzESic
"""

#1_2) Come up with an O(N)solution.
#Code here

inp = open("input1_2.txt", "r")
out = open("output1_2.txt", "w")

n, s = map(int, inp.readline().split())
list_of_numbers = list(map(int, inp.readline().split()))

num_dict = {}

for index, num in enumerate(list_of_numbers):
    complement = s - num
    if complement in num_dict:
        index1 = num_dict[complement]
        index2 = index
        out.write(f"{index1 + 1}, {index2 + 1}\n")
        break
    num_dict[num] = index
else:
    out.write("IMPOSSIBLE\n")
inp.close()
out.close()