# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlRMQI2ibgYNauaPtmqE_aZXV7RzESic
"""

#Task 3
#Code here

inp = open("input3.txt", "r")
oup = open("output3.txt", "w")

n = int(inp.readline().strip())
intervals = []
for i in range(n):
    start, end = map(int, inp.readline().split())
    intervals.append((start, end))

intervals.sort(key=lambda x: x[1])

selected_tasks = []
previous_end_time = -1
for interval in intervals:
    start, end = interval
    if start >= previous_end_time:
        selected_tasks.append(interval)
        previous_end_time = end

k = len(selected_tasks)

oup.write(str(k) + "\n")
for interval in selected_tasks:
    oup.write(str(interval[0]) + " " + str(interval[1]) + "\n")

inp.close()
oup.close()