# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEiAwmE-dJsIOXbwDGMQs7O5YNpNaaR_
"""

#Task 04

def max_sum_of_squares(arr):
    n = len(arr)

    arr.sort()

    max_sum = -float("inf")

    for i in range(n):
        for j in range(i+1, n):
            current_sum = arr[i] + arr[j] ** 2
            max_sum = max(max_sum, current_sum)

    return max_sum

inp = open("input4.txt", "r")
oup = open("output4.txt", "w")

N = int(inp.readline())
A = list(map(int, inp.readline().split()))

result = max_sum_of_squares(A)
oup.write(str(result))

inp.close()
oup.close()