# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEiAwmE-dJsIOXbwDGMQs7O5YNpNaaR_
"""

#Task 05

def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1

    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quick_sort(arr, low, high):
    if low < high:
        pivot_index = partition(arr, low, high)
        quick_sort(arr, low, pivot_index - 1)
        quick_sort(arr, pivot_index + 1, high)

inp = open("input5.txt", "r")
oup = open("output5.txt", "w")


N = int(inp.readline())
numbers = list(map(int, inp.readline().split()))

quick_sort(numbers, 0, N - 1)

oup.write(" ".join(map(str, numbers)))

print(".")