# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEiAwmE-dJsIOXbwDGMQs7O5YNpNaaR_
"""

#Task 01:

def merge(a, b):
    c = []
    i, j = 0, 0
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            c.append(a[i])
            i += 1
        else:
            c.append(b[j])
            j += 1
    c += a[i:]
    c += b[j:]
    return c

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        a1 = mergeSort(arr[:mid])
        a2 = mergeSort(arr[mid:])
        return merge(a1, a2)

inp = open("input1.txt", "r")
oup = open("output1.txt", "w")

n = int(inp.readline())
arr = list(map(int, inp.readline().strip().split()))

sorted_arr = mergeSort(arr)
oup.write(' '.join(map(str, sorted_arr)))

inp.close()
oup.close()