# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEiAwmE-dJsIOXbwDGMQs7O5YNpNaaR_
"""

#Task 02:

def find_max(arr, start, end):
    if start == end:
        return arr[start]
    mid = (start + end) // 2
    left_max = find_max(arr, start, mid)
    right_max = find_max(arr, mid+1, end)
    return max(left_max, right_max)


inp = open("input2.txt", "r")
oup = open("output2.txt", "w")


n = int(inp.readline())
arr = list(map(int, inp.readline().split()))
result = find_max(arr, 0, n-1)
oup.write(str(result))

print(".")

inp.close()
oup.close()