# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1MItGQGv0FVTQhtjrgVzVxT_RUqS9PM
"""

#Task-1 (B)

inp = open("input1_b.txt", "r")
oup = open("output1_b.txt", "w")

n, m = map(int, inp.readline().split())

adj_list = {i: [] for i in range(n)}


for i in range(m):
  u, v, w = map(int, inp.readline().split())
  adj_list[u-1].append((v-1, w))

for u in range(n):
    oup.write(f"{u} : ")
    for v, w in adj_list[u]:
        oup.write(f"({v+1},{w}) ")
    oup.write("\n")
oup.close()