# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1MItGQGv0FVTQhtjrgVzVxT_RUqS9PM
"""

#Task-2

def readInput(filename):
	with open(filename, "r") as f:
	    edges = []
	    for line in f:
	        u, v = line.strip().split()
	        u = int(u)
	        v = int(v)
	        edges.append((u, v))
	return edges


def bfs(edges, start):
    neighbors = {}
    for u, v in edges:
        if u not in neighbors:
            neighbors[u] = []
        if v not in neighbors:
            neighbors[v] = []
        neighbors[u].append(v)
        neighbors[v].append(u)

    visited = set()
    queue = [start]

    results = []

    while queue:
        u = queue.pop(0)

        if u not in visited:
            visited.add(u)
            results.append(u)
            print(u, end = " ")
            for v in neighbors[u]:
                if v not in visited:
                    queue.append(v)
    return results


def writeOutput(filename, results):
	with open(filename, "w") as f:
	    for num in results:
	        f.write(str(num) + " ")



#Sample test case 1
edges = readInput("2_sample_input1.txt")
results = bfs(edges, 1)
writeOutput("2_sample_output1.txt", results)
print()

#Sample test case 2
edges = readInput("2_sample_input2.txt")
results = bfs(edges, 1)
writeOutput("2_sample_output2.txt", results)
print()


#Sample test case 3
edges = readInput("2_sample_input3.txt")
results = bfs(edges, 1)
writeOutput("2_sample_output3.txt", results)
print()