# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YipZk2cBmJM9BSMA44bCaCfZamSXDjtY
"""

input=open('input4.txt','r')
output=open('output4.txt','w')
size=int(input.readline())
id=(input.readline().split(' '))
mark=(input.readline().split(' '))
for i in range(len(id)):
  id[i]=int(id[i])
  mark[i]=int(mark[i])
nested=[None]*size
for i in range(len(nested)):
  nested[i]=[id[i],mark[i]]
def selectionsort(a):
  for i in range(len(a)-1):
    minidx=i
    for j in range(i+1,len(a)):
      if a[j][1]>a[minidx][1]:
        minidx=j
    temp=a[i][0]
    temp2=a[i][1]
    a[i][0]=a[minidx][0]
    a[i][1]=a[minidx][1]
    a[minidx][0]=temp
    a[minidx][1]=temp2
  return a
sortnest=selectionsort(nested)
for i in range(len(sortnest)):
  output.write(f'ID: {sortnest[i][0]} Mark: {sortnest[i][1]}\n')
input.close()
output.close()