# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17tjSbLME5z8jDZ6gJMJZAiu7tmTgKPMZ
"""

#1a
finput=open('input1a.txt','r')
foutput=open('output1a.txt','w')
n=int(finput.readline())

for i in range(n):
  check=int(finput.readline())
  if check%2==0:
    foutput.write(f'{check} is an even number\n')
  else:
    foutput.write(f'{check} is an odd number\n')

finput.close()
foutput.close()

#1b
input=open('input1b.txt','r')
output=open('output1b.txt','w')
n=int(input.readline())
for i in range(n):
  line=input.readline()
  line=line.replace('calculate ','')
  if '+' in line:
    num1,num2=line.split(' + ')
    result=int(num1)+int(num2)
  elif '-' in line:
    num1,num2=line.split(' - ')
    result=int(num1)-int(num2)
  elif '*' in line:
    num1,num2=line.split(' * ')
    result=int(num1)*int(num2)
  elif '/' in line:
    num1,num2=line.split(' / ')
    result=int(num1)/int(num2)
  output.write(f'The result of {line} is {result}\n')
  
input.close()
output.close()