# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YhlMFgvq7TnDTA0RIkKsJyaKoTJz3mbI
"""

input=open('input5.txt','r')
output=open('output5.txt','w')
size=int(input.readline())
lines=[]
lines2=[]
names=[]
times=[]
for i in range(size):
  line=input.readline()
  lines.append(line[:-1])
for i in range(len(lines)):
  a=lines[i].split(' ')
  lines2.append(a)
  names.append(lines2[i][0])
  times.append(int(lines2[i][-1].replace(':','')))

def selectionsort(size,lines,names,times):
  for i in range(size):
    minidx=i
    for j in range(i+1,size):
      if names[j]<=names[minidx]:
        if names[j]==names[minidx]:
          if names[j]>names[minidx]:
              minidx=j
        else:
          minidx=j     
    lines[i],lines[minidx]=lines[minidx],lines[i]
    times[i],times[minidx]=times[minidx],times[i]
    names[i],names[minidx]=names[minidx],names[i]
selectionsort(size,lines,names,times)
for i in range(size):
  output.write(lines[i]+'\n')
input.close()
output.close()